config/routes.rb
Rails.application.routes.draw do
  resources :shots do 
  	resources :comments 
  	member do 
  		put 'like', to: "shots#like"
  		put 'unlike', to: "shots#unlike"
  	end
  end
 
  devise_for :users, controllers: { registrations: 'registrations' }
  
  root 'shots#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :shot 
    belongs_to :user
end

app/models/shot.rb
class Shot < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	
	mount_uploader :user_shot, UserShotUploader
	is_impressionable
	acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shots, dependent: :destroy
  has_many :comments, dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:creat, :destroy]
  
  def create
    @shot = Shot.find(params[:shot_id])
    @comment = @shot.comments.create(comment_params)
    @comment.user_id = current_user.id if current_user 
    @comment.save!

    redirect_to shot_path(@shot)
    end
  end

  def destroy
    @shot = Shot.find(params[:shot_id])
    @comment = @shot.comments.find(params[:id])
    @comment.destroy 
    redirect_to shot_path(@shot)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :response)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
# https://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html
class RegistrationsController < Devise::RegistrationsController

    private
   
     def sign_up_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation)
     end
   
     def account_update_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
     end
   
   end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :like, :unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

  # GET /shots
  # GET /shots.json
  def index
    @shots = Shot.all.order('created_at DESC')
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots
  # POST /shots.json
  def create
    @shot = current_user.shots.build(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to @shot, notice: 'Shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1
  # PATCH/PUT /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot.destroy
    respond_to do |format|
      format.html { redirect_to shots_url, notice: 'Shot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @shot.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  def unlike
    @shot.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shot_params
      params.require(:shot).permit(:title, :description, :user_shot)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def verbose_date(date)
		date.strftime('%B %d %Y')
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <p class="image is-48x48 user-thumb">
        <%= gravatar_image_tag(comment.user.email.gsub('spam', 'mdeering'), alt: comment.user.name, gravatar: { size: 48 }) %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong>
          <div><%= comment.response %></div>
        </p>
      </div>
    </div>
    <% if (user_signed_in? && (current_user.id == comment.user_id)) %>
       <%= link_to 'Delete', [comment.shot, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@shot, @shot.comments.build]) do |f| %>

	<div class="field">
		<div class="control">
			<%= f.input :name, input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label' } %>
		</div>
	</div>

	<div class="field">
		<div class="control">
			<%= f.input :response, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
		</div>
	</div>
	
	<%= f.button :submit, 'Leave a reply', class: 'button is-primary' %>
<% end %>
© 2020 GitHub, Inc.

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DribbbleClone</title>
    <%= csrf_meta_tags %>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
    	<div class="notification is-primary global-notification">
  	  	<p class="notice"><%= notice %></p>
    	</div>
   	<% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5 has-text-white">Dribbble Clone</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">

        <div class="navbar-start">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Shots', root_path , class:"button is-dark" %>
              </p>
            </div>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
              <p class="control">
                <%= link_to new_shot_path, class:"button is-primary"  do %>
                  <span class="icon is-small"><i class="fa fa-upload"></i></span>
                  <span>New Shot</span>
                <% end %>
              </p>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class:"button is-dark" %>
              </p>
              <p class="control">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"button is-dark" %>
              </p>
              <% else %>
              <p class="control">
                 <%= link_to "Sign In", new_user_session_path, class:"button is-dark" %>
              </p>
              <p class="control">
                <%= link_to "Sign up", new_user_registration_path, class:"button is-dark"%>
              </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav> 

    <%= yield %>
  </body>
</html>

app/views/shots/_form.html.erb
<%= simple_form_for @shot, html: { multipart: true }  do |f| %>
  <%= f.error_notification %>
  <div class="columns is-centered">
    <div class="column is-half">
    
    <% unless @shot.user_shot.blank? %>
    <%= image_tag (@shot.user_shot_url), id: "previewImage" %>
    <% end %>

    <output id="list"></output>
    <div id="drop_zone">Drag your shot here</div>
    <br />

    <%= f.input :user_shot, label: false, input_html: { class: "file-input", type: "file" }, wrapper: false, label_html: { class: "file-label" } %>

    <div class="field">
      <div class="control">
      	<%= f.input :title, label: "Title", input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
    	<div class="control">
      	<%= f.input :description, input_html: { class: "textarea"}, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
    	<div class="control">
      	<%= f.button :submit, class:"button is-primary" %>
      </div>
    </div>
  </div>
</div>

 
<% end %>

app/views/shots/_hero.html.erb
<% if !user_signed_in? %>
	<section class="hero is-dark">
		<div class="hero-body">
			<div class="container has-text-centered">
				<h1 class="title is-size-5">
					What are you working on? <span class="has-text-grey-light">Dribbble is where designers get inspired and hired.</span>
				</h1>
				<div class="content">
					<%= link_to "Login", new_user_session_path, class: "button is-primary" %>
				</div>
			</div>
		</div>
	</section>
<% end %>

app/views/shots/edit.html.erb
<section class="section">
	<div class="container">
		<h1 class="title has-text-centered">Editing Shot</h1>
		<%= render 'form', shot: @shot  %>
	</div>
</section>

app/views/shots/index.html.erb
<%= render 'hero' %>

<section class="section">
  <div class="shots">
    <% @shots.each do |shot| %>
      <div class="shot-grid-item">
        <div class="shot-wrapper">
          
        <%= link_to shot, class: "shot" do %>
          <%= image_tag(shot.user_shot_url) %>
          <div class="shot-data">
            <h3 class="shot-title"><%= shot.title %></h3>
            <div class="shot-description"><%= truncate(shot.description, length: 60) %></div>
            <div class="shot-time">
              <%= time_ago_in_words(shot.created_at) %>
            </div>
          </div>
        <% end %>

        <nav class="level shot-analytics">
          <div class="level-left"></div>
          <div class="level-right">
            <div class="level-item views data">
              <%= link_to shot do %>
                <span class="icon"><i class="fa fa-eye"></i></span>
                <%= shot.impressionist_count %>
              <% end %>
            </div>
            <div class="level-item comments data">
              <%= link_to shot do %>
                <span class="icon"><i class="fa fa-comment"></i></span>
                 <%= shot.comments.count %>
              <% end %>
            </div>
            <div class="level-item likes">
              <% if user_signed_in? %>
                
                <% if current_user.liked? shot %>
                  <%= link_to unlike_shot_path(shot), method: :put, class: "unlike_shot" do %>
                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                    <span class="vote_count"><%= shot.get_likes.size %></span>
                  <% end %>
                <% else %>
                  <%= link_to like_shot_path(shot), method: :put, class: "like_shot" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= shot.get_likes.size %></span>
                  <% end %>
                <% end %>
              <% else %>
                  <%= link_to like_shot_path(shot), method: :put, class: "like_shot" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= shot.get_likes.size %></span>
                  <% end %>
              <% end %>

            </div>
          </div>
        </nav>
        </div>
        <div class="user-data">
          <div class="user-thumb">
            <%= gravatar_image_tag(shot.user.email.gsub('spam', 'mdeering'), alt: shot.user.name, gravatar: { size: 20 }); %>
          </div>
          <div class="user-name"><%= shot.user.name %></div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/shots/new.html.erb
<section class="section">
	<div class="container">
		<h1 class="title is-2 has-text-centered">What are you working on?</h1>
		<%= render 'form', shot: @shot %>
	</div>
</section>

app/views/shots/show.html.erb
<div class="section">
	<div class="container">
		<h1 class="title is-3"><%= @shot.title %></h1>
		<div class="columns">
			<div class="column is-8">
				<span class="by has-text-grey-light">by</span>
				<div class="user-thumb">
					<%= gravatar_image_tag(@shot.user.email.gsub('spam', 'mdeering'), alt: @shot.user.name, gravatar: { size: 20 }); %>
				</div>
				<div class="user-name has-text-weight-bold"><%= @shot.user.name %></div>
				<div class="shot-time"><span class="has-text-grey-light">posted</span><span class="has-text-weight-semibold">
					<%= verbose_date(@shot.created_at) %>
				</span></div>
			</div>	
		</div>

		<div class="columns">
			<div class="column is-8">
				<div class="shot-container">
					<div class="shot-full">
						 <%= image_tag @shot.user_shot_url unless @shot.user_shot.blank? %>
					</div>

					<% if user_signed_in? && (current_user.id == @shot.user_id) %>		
						<div class="buttons has-addons">
							<%= link_to 'Edit', edit_shot_path(@shot), class: "button" %>
							<%= link_to 'Delete', shot_path, class: "button", method: :delete, data: { confirm: 'Are you sure you want to delete this shot?'} %>
						</div>
					<% end %>

					<div class="content">
						<%= @shot.description %>
					</div>

					<section class="comments">
						<h2 class="subtitle is-5"><%= pluralize(@shot.comments.count, 'Comment') %></h2>
							<%= render @shot.comments %>
						<hr />
						<% if user_signed_in? %>
							<div class="comment-form">
								<h3 class="subtitle is-3">Leave a reply</h3>
								<%= render 'comments/form' %>
							</div>
						<% else %>
							<div class="content"><%= link_to 'Sign in', new_user_session_path %> to leave a comment.</div>
						<% end %>
					</section>

				</div>
			</div>
			<div class="column is-3 is-offset-1">
				<div class="nav panel show-shot-analytics">
					<div class="panel-block views data">
						<span class="icon"><i class="fa fa-eye"></i></span>
						<%= pluralize(@shot.impressionist_count, 'View') %>
					</div>
					<div class="panel-block comments data">
						<span class="icon"><i class="fa fa-comment"></i></span>
						<%= pluralize(@shot.comments.count, 'Comment') %>
					</div>
					<div class="panel-block likes data">
						<% if user_signed_in? %>
              <% if current_user.liked? @shot %>
                <%= link_to unlike_shot_path(@shot), method: :put, class: "unlike_shot" do %>
                  <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                  <span class="vote_count"><%= pluralize(@shot.get_likes.size, 'Like') %></span>
                <% end %>
              <% else %>
                <%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
                  <span class="icon"><i class="fa fa-heart"></i></span>
                  <span class="vote_count"><%= pluralize(@shot.get_likes.size, 'Like') %></span>
                <% end %>
              <% end %>
            <% else %>
                <%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
                  <span class="icon"><i class="fa fa-heart"></i></span>
                  <span class="vote_count"><%= pluralize(@shot.get_likes.size, 'Like') %></span>
                <% end %>
            <% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>